---
- name: Make sure eZSolr install dir exists
  become: yes
  file:
      state: directory
      path: "{{ ezsolr.install_dir }}"
      mode: 0755
      owner: "{{ ansible_user_id }}"

- name: Downloading eZSolr
  get_url:
      url: "{{ ezsolr.download_url }}"
      dest: "/tmp/solr.downloaded"

- name: Unarchive eZSolr from URL
  shell: "unzip /tmp/solr.downloaded 'java/*' && mv java ezsolr"
  args:
      chdir: "{{ ezsolr.install_dir }}"
      creates: ezsolr/start.jar
      warn: no

- name: Add Solr start/stop script
  become: yes
  template:
      src: "solr.j2"
      dest: /etc/init.d/solr
      mode: 0755
  notify: restart init solr

- name: Configure Systemd service for Solr
  become: yes
  template:
      src: "solr.service.j2"
      dest: /lib/systemd/system/solr.service
      mode: 0644
  notify:
      - enable solr
      - restart solr

- name: Create cores directories
  become: yes
  shell: "cd {{ ezsolr.install_dir }}/ezsolr/solr && if [ ! -f {{ item.name }}/conf/schema.xml ]; then rsync -au ezp-default/ {{ item.name }}/; fi "
  with_items: "{{ ezsolr.cores }}"
  changed_when: False

- name: Add Synonyms file
  template:
      src: synonyms.txt.j2
      dest: "{{ ezsolr.install_dir }}/ezsolr/solr/{{ item.name }}/conf/synonyms.txt"
  with_items: "{{ ezsolr.cores }}"
  notify: restart solr
  tags: synonyms

- name: Configure eZSolr cores
  template:
      src: solr.xml.j2
      dest: "{{ ezsolr.install_dir }}/ezsolr/solr/solr.xml"
  notify: restart solr
