---
- name: Make sure eZSolr install dir exists
  sudo: yes
  file:
    state: directory
    path: "{{ ezsolr['install_dir'] }}"
    mode: 0755
    owner: "{{ ansible_user_id }}"

- name: Add composer.json with ezfind
  template:
    src: "composer.json.j2"
    dest: "{{ ezsolr['install_dir'] }}/composer.json"
  notify: restart solr

- name: Install eZFind with composer
  composer:
      command: install
      working_dir: "{{ ezsolr['install_dir'] }}"

- name: Add Solr start/stop script
  sudo: yes
  template:
    src: "solr.j2"
    dest: /etc/init.d/solr
    mode: 0755
  notify: restart solr

- name: Create cores directories
  sudo: yes
  shell: "cd {{ ezsolr['install_dir'] }}/extension/ezfind/java/solr && rsync -au ezp-default/ {{ item }}/"
  with_items: ezsolr['cores']
  changed_when: False

- name: Configure eZSolr cores
  template:
    src: solr.xml.j2
    dest: "{{ ezsolr['install_dir'] }}/extension/ezfind/java/solr/solr.xml"
  notify: restart solr
